### ISSUE TITLE
Magma Not Supported

### ISSUE THREAD

**Issue by MattRamsey** [mitre/caldera-ot#3]
Any roadmap to get Caldera 5.0.0 supported to run these plugins ?  I'm able to load them but get this Warning

![image](https://github.com/mitre/caldera-ot/assets/80547100/d5d0641f-bd36-49c1-8367-f233dcb017f6)

**Comment by d3vco** [comment]
Yesterday's commit e095f56f5108b276e68b6f428b96d1c5639e6f0d added support for Caldera v5 (Magma). Please let us know if you have any issues with the updated plugins.

Also note that if you are using the iec61850 plugin, the install instructions have changed slightly as documented in the [README](https://github.com/mitre/caldera-ot?tab=readme-ov-file#installing-the-iec-61850-payloads).
